#pragma once

#include <Windows.h>
#include <dwmapi.h>

#define HOOK_COMCTL32_OPENNCTHEMEDATA_ARGS      "comctl32.dll", "uxtheme.dll", nullptr, 49, true

NATIVES_EXPORT void NATIVESAPI EnableDarkModeForApp(BOOL enabled);

#define HOOK_COMCTL32_GETSYSCOLOR_ARGS			"comctl32.dll", "user32.dll", "GetSysColor", 0, false

NATIVES_EXPORT void NATIVESAPI ComctlHookSysColor(COLORREF crFore, COLORREF crBack);
NATIVES_EXPORT void NATIVESAPI ComctlUnhookSysColor();

#define HOOK_COMCTL32_OPENTHEMEDATAFORDPI_ARGS	"comctl32.dll", "uxtheme.dll", "OpenThemeDataForDpi", 0, true

NATIVES_EXPORT void NATIVESAPI ComctlHookOpenTheme();
NATIVES_EXPORT void NATIVESAPI ComctlUnhookOpenTheme();

#define HOOK_COMDLG32_GETSYSCOLORBRUSH_ARGS     "comdlg32.dll", "user32.dll", "GetSysColorBrush", 0, false

NATIVES_EXPORT void NATIVESAPI ComdlgHookGetSysColorBrush();
NATIVES_EXPORT void NATIVESAPI ComdlgUnhookGetSysColorBrush();

#define DWMWA_USE_IMMERSIVE_DARK_MODE_BEFORE_20H1 19

NATIVES_EXPORT void NATIVESAPI EnableDarkModeForWindowFrame(HWND hWnd, BOOL after20h1, BOOL enabled);

NATIVES_EXPORT void NATIVESAPI SetWindowBorderColor(HWND hWnd, COLORREF color, BOOL enabled);
NATIVES_EXPORT DWORD NATIVESAPI GetSystemAccentColor();

typedef enum _WINDOWCOMPOSITIONATTRIB
{
    WCA_UNDEFINED = 0,
    WCA_NCRENDERING_ENABLED,
    WCA_NCRENDERING_POLICY,
    WCA_TRANSITIONS_FORCEDISABLED,
    WCA_ALLOW_NCPAINT,
    WCA_CAPTION_BUTTON_BOUNDS,
    WCA_NONCLIENT_RTL_LAYOUT,
    WCA_FORCE_ICONIC_REPRESENTATION,
    WCA_EXTENDED_FRAME_BOUNDS,
    WCA_HAS_ICONIC_BITMAP,
    WCA_THEME_ATTRIBUTES,
    WCA_NCRENDERING_EXILED,
    WCA_NCADORNMENTINFO,
    WCA_EXCLUDED_FROM_LIVEPREVIEW,
    WCA_VIDEO_OVERLAY_ACTIVE,
    WCA_FORCE_ACTIVEWINDOW_APPEARANCE,
    WCA_DISALLOW_PEEK,
    WCA_CLOAK,
    WCA_CLOAKED,
    WCA_ACCENT_POLICY,
    WCA_FREEZE_REPRESENTATION,
    WCA_EVER_UNCLOAKED,
    WCA_VISUAL_OWNER,
    WCA_HOLOGRAPHIC,
    WCA_EXCLUDED_FROM_DDA,
    WCA_PASSIVEUPDATEMODE,
    WCA_USEDARKMODECOLORS,
    WCA_CORNER_STYLE,
    WCA_PART_COLOR,
    WCA_DISABLE_MOVESIZE_FEEDBACK,
    WCA_SYSTEMBACKDROP_TYPE,
    WCA_SET_TAGGED_WINDOW_RECT,
    WCA_CLEAR_TAGGED_WINDOW_RECT,
    WCA_REMOTEAPP_POLICY,
    WCA_HAS_ACCENT_POLICY,
    WCA_REDIRECTIONBITMAP_FILL_COLOR,
    WCA_REDIRECTIONBITMAP_ALPHA,
    WCA_BORDER_MARGINS,
    WCA_LAST
} WINDOWCOMPOSITIONATTRIB;

typedef enum _ACCENT_STATE
{
    ACCENT_DISABLED,
    ACCENT_ENABLE_GRADIENT,
    ACCENT_ENABLE_TRANSPARENTGRADIENT,
    ACCENT_ENABLE_BLURBEHIND,
    ACCENT_ENABLE_ACRYLICBLURBEHIND,
    ACCENT_ENABLE_HOSTBACKDROP,
    ACCENT_INVALID_STATE
} ACCENT_STATE;

typedef enum _ACCENT_FLAG
{
    ACCENT_NONE,
    ACCENT_WINDOWS11_LUMINOSITY = 0x2,
    ACCENT_BORDER_LEFT = 0x20,
    ACCENT_BORDER_TOP = 0x40,
    ACCENT_BORDER_RIGHT = 0x80,
    ACCENT_BORDER_BOTTOM = 0x100,
    ACCENT_BORDER_ALL = (ACCENT_BORDER_LEFT | ACCENT_BORDER_TOP | ACCENT_BORDER_RIGHT | ACCENT_BORDER_BOTTOM)
} ACCENT_FLAG;

typedef struct tagWINDOWCOMPOSITIONATTRIBUTEDATA
{
    WINDOWCOMPOSITIONATTRIB Attribute;
    PVOID pvData;
    SIZE_T cbData;
} WINDOWCOMPOSITIONATTRIBUTEDATA, *LPWINDOWCOMPOSITIONATTRIBUTEDATA;

typedef struct _ACCENT_POLICY
{
    ACCENT_STATE AccentState;
    DWORD AccentFlags;
    DWORD dwGradientColor;
    DWORD dwAnimationId;
} ACCENT_POLICY, *PACCENT_POLICY;

#define DWMWA_MICA_EFFECT               1029

#define ASB_BACKDROP_TYPE_MASK          0x0000000F
#define ASBT_AUTO                       DWMSBT_AUTO
#define ASBT_NONE                       DWMSBT_NONE
#define ASBT_ACRYLIC                    DWMSBT_TRANSIENTWINDOW
#define ASBT_MICA                       DWMSBT_MAINWINDOW
#define ASBT_MICAALT                    DWMSBT_TABBEDWINDOW
#define ASBT_AERO                       5

#define ASB_FORCE_OPTIONS_MASK          0x000000F0
#define ASBF_WIN10_ACRYLIC              0b00000001
#define ASBF_ALLOW_AERO                 0b00000010
#define ASBF_USE_DWMAPI                 0b00000100

#define ASB_STATUS_MASK                 0x00000F00
#define ASBS_DISABLED                   FALSE;
#define ASBS_ENABLED                    TRUE;

#define ASB_GET_BACKDROP(dw)            (((DWORD)(dw)) & ASB_BACKDROP_TYPE_MASK)
#define ASB_GET_FOPTIONS(dw)            ((((DWORD)(dw)) & ASB_FORCE_OPTIONS_MASK) >> 4)
#define ASB_GET_STATUS(dw)              ((((DWORD)(dw)) & ASB_STATUS_MASK) >> 8)
#define ASB_DEFINED_FOPTIONS(dw, op)    (ASB_GET_FOPTIONS(dw) & op)

NATIVES_EXPORT BOOL NATIVESAPI ApplySystemBackdrop(HWND hWnd, DWORD dwFlags, PVOID pvData);
