name: ✨ 功能建议
description: 您希望我们可以添加的功能
title: "✨ [New] "
labels: ["新功能"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您致力于帮助本程序变得更实用！

  - type: checkboxes
    id: verify
    attributes:
      label: ⭕ 确认事项
      description: 请根据你的实际情况勾选以下项目
      options:
        - label: 我正在使用的是最新版本
          required: true
        - label: 我已确认没有重复提交相同或类似的功能建议
          required: true

  - type: textarea
    id: suggest
    attributes:
      label: ⭕ 功能描述
      description: 请详细描述你希望添加的功能，以及它能为用户带来哪些帮助或解决什么问题
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: ⚪ [选填] 可能的实现方法
      description: 如果你对该功能的实现有思路，欢迎在此补充，可以是文字说明或相关代码
    validations:
      required: false
