#pragma once

#define WC_PLAINTIMESPANPICK L"PlainTimeSpanPick"

#define PTSPM_GETVALUE (WM_USER + 0x0010)
#define PTSPM_SETVALUE (WM_USER + 0x0011)
#define PTSPM_GETDAYSMAX (WM_USER + 0x0012)
#define PTSPM_SETDAYSMAX (WM_USER + 0x0013)
#define PTSPM_OVERRIDECOLORS (WM_USER + 0x0014)
#define PTSPM_QUERYMAXSIZE (WM_USER + 0x0015)

#define PTSPN_VALUECHANGE 1

#define PTSPCOLOR_RESTORE 0xFF
#define PTSPCOLOR_BACKTEXT 0
#define PTSPCOLOR_FORETEXT 1
#define PTSPCOLOR_FORETEXTDISABLED 2

#define PTSPCOLOR_GET_PART_LPARAM(lp) ((BYTE)((((DWORD_PTR)(lp)) >> 24) & 0xFF))
#define PTSPCOLOR_GET_COLOR_LPARAM(lp) ((COLORREF)(((DWORD_PTR)(lp)) & 0xFFFFFF))

typedef LONGLONG TIMESPAN, *LPTIMESPAN;

typedef struct tagCTRLCOLORS
{
    COLORREF backText;
    COLORREF foreText;
    COLORREF foreTextDisabled;
} CTRLCOLORS, *LPCTRLCOLORS;

#define TICKS_PER_SECOND      10000000LL
#define TICKS_PER_MINUTE      (TICKS_PER_SECOND * 60LL)
#define TICKS_PER_HOUR        (TICKS_PER_MINUTE * 60LL)
#define TICKS_PER_DAY         (TICKS_PER_HOUR * 24LL)

#define MAKETIMESPAN(d, h, m, s) \
    ((TIMESPAN)(((LONGLONG)(d) * TICKS_PER_DAY) + \
     ((LONGLONG)(h) * TICKS_PER_HOUR) + \
     ((LONGLONG)(m) * TICKS_PER_MINUTE) + \
     ((LONGLONG)(s) * TICKS_PER_SECOND)))

#define GET_DAYS_TIMESPAN(ts)        (INT)((LONGLONG)(ts) / TICKS_PER_DAY)
#define GET_HOURS_TIMESPAN(ts)       (INT)(((LONGLONG)(ts) / TICKS_PER_HOUR) % 24LL)
#define GET_MINUTES_TIMESPAN(ts)     (INT)(((LONGLONG)(ts) / TICKS_PER_MINUTE) % 60LL)
#define GET_SECONDS_TIMESPAN(ts)     (INT)(((LONGLONG)(ts) / TICKS_PER_SECOND) % 60LL)

#define TIMESPAN_MIN ((TIMESPAN)INT64_MIN)
#define TIMESPAN_ZERO ((TIMESPAN)0LL)
#define TIMESPAN_MAX ((TIMESPAN)INT64_MAX)

#define TIMESPAN_DAYS_MIN (GET_DAYS_TIMESPAN(TIMESPAN_MIN))
#define TIMESPAN_DAYS_ZERO 0
#define TIMESPAN_DAYS_MAX (GET_DAYS_TIMESPAN(TIMESPAN_MAX))

#define PTSP_SEG_BUFFER 10

cexport(ATOM) PlainTimeSpanPick_RegisterWC();