name: PlainCEETimer CI/CD Builder

on:
  push:
    branches:
      - main
    paths:
      - 'PlainCEETimer/**'
      - 'PlainCEETimer.Natives/**'
      - 'PlainCEETimer.Setup/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Restore Solution
        run: nuget restore

      - name: Build Project
        run: msbuild /p:Configuration=Release

      - name: Build Setup
        run: makensis PlainCEETimer.Setup/Setup.nsi

      - name: Upload to Pre-Release
        uses: softprops/action-gh-release@v1
        with:
            tag_name: preview
            release_name: Preview
            prerelease: true
            overwrite: true
            files:
              - PlainCEETimer.Setup\*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}