name: CI Build

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: true
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    permissions: write-all
    uses: ./.github/workflows/common.yml
    with:
      release-type: ci
      prerelease: true
      static-json-name: ci.json
      static-download-dir: download/ci
      static-commit-prefix: 'ci:'
      static-delete-pattern: 'download/ci/*'
    secrets: inherit
