name: Stable Build

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: true
  push:
    branches:
      - main
    paths:
      - '.github/triggers/stable-release'

jobs:
  build:
    permissions: write-all
    uses: ./.github/workflows/common.yml
    with:
      release-type: stable
      prerelease: false
      static-json-name: github.json
      static-download-dir: download
      static-commit-prefix: 'main:'
      static-delete-pattern: 'download/*.exe'
    secrets: inherit
